### PR TITLE
Upgrade Matterfoss to v6.6.1

### PR DESCRIPTION
**Pull request by thierrymarianne**
# Notes

 - During the kick-off meeting, we agreed on upgrading the server to `v6.3.6`
 - However I decided to upgrade to `v6.6.1` on my own accord 
   (a security fix was released some days ago),
   after i had started to work on merging `v6.6.0`.
   I thought it would be a shame to have the server upgraded 
   only to have it incompatible again with the mobile apps little time afterwards.

# Server build

```
export GO111MODULE=on  && go build -gcflags "all=-N -l" -o ./bin ./...
```

# Server run

```
./bin/matterfoss >>./log/app.log 2>&1 & disown
``` 

Tests have been conducted with `go1.18.1 linux/amd64`

# Schedule

schedule-pkt-chat-upgrade

[Timesheet from 2022-04-12 to 2022-05-04 (CSV file)](https://github.com/cjdelisle/Matterfoss/files/8622378/2022-04-12_to_2022-05-04_pkt_chat_upgrade.csv)

### CODE REVIEW

**Comment by cjdelisle** [comment]
🎉 

Can't wait to start reviewing this !

**Comment by cjdelisle** [comment]
Thank you very much, I was not expecting to see this today!

**Comment by cjdelisle** [comment]
I can't merge this in it's current form because it reverts all of the license, telemetry, and other changes which have been made to MatterFOSS.
I pushed a branch here: https://github.com/cjdelisle/Matterfoss/tree/thierry-merge2 which is identical to your branch, except without commit/revert of our changes, so that merging in these changes will work.

The commit hashes which need to be merged back in are:

```
bc84a6bb554971120e4e2b8bc38158b278379a99
30d56ab6306226284a82271932d0553b780e17fa
83fc94072cca549c2d1f7c029b56381dd17d83d7
9f33ab31d1c090eb12251c56b153c8f12e01d6e9
5d9c3023162479e1442a78ccd26ff26cb59a1b91
62be42f3dd44748300b748121c49164db65d0b1b
9461665b3aaf167501e44bc9ff295a77f512ef12
5900dca52a7ef34bd9b2fa0716185f0482ad41ef
93f538ac7c18c961b2ec102bd83739decc56eaf8
262d604c38538917ae8cd4a7008e427fa4db0735
ca1385dd5bf32f01360800038469591ad8bfe89d
a3318be93a6ca734364aae5b07d41a870a80d06a
c8588ec6c749bffc8ec3c8a8bab3b661a3241913
3f9d3cfaa8b4df2ca7dff21e8757630d7c028ab1
ed8ac08587150e9bfb6941027f89dc4bea904249
259cf4731f86bdc1875d009b270adf62fe517d73
fcf458d0ed0d912bd7d1ab27c80a18c73e5e083c
2dbbb7ade8bae31faa61400412650c0da6bec38f
7a54ed5cdc21ad6a9194b34fc6733e55e5b7dd6c
7f261e6acf263f1e4a9a623e4c656d50ca4d0c45
bbb47971d9500315466d8a6fa37d42fd8622454b
555ad5e05bfdac62f3fe44e26676f901fae877bc
992033c3db9e7ed359cd88b8c62e9bba85531cbb
12bb9a208ef4db22ef329e48a3285f0a3b5bf18f
9c70b627ed815930c53ab381d12f1ed0ab5467fe
04d6d49177f3b44c53d4a10b026b497d8ceb2b4a
f559ba6a91f97e4c2ca1bcbb1988358c51e04921
50b9bedf3b5e9cc69bb7909fd13ed11d95659f0d
9ae01927be3454b9f589a856cf2903fee5699ca5
388e850b205915d2b27df4aa131c2cb124505166
4a8953c5234b5f86f6b07fbdec6bfef2dc7fd12f
8e42cbde3ddd3aba2000e7def60543240cea73ac
60adfe5d402d1e981b548404c76cbda43c5c53e7
5008f07e81539d1085506129f8c4345affe8fdab
22cd865ed8318bd4a9de1f309009a2a09365c042
06b5ebb69b6c04d235da576d869e2e469223ccc9
b42c28ab55bc590cf0a92ada916671968db20376
99b26af24bf63be55acc3ba0e67843a0a36506e0
1e9b15aac52b23a16da43e334e6cd45deb1daae6
f4f95ae73ef4f8a8bcbbbc7503d69ef526182190
6ee12ad8c17851e466211a82113510735fbad010
7acc2ca0310b3f042462902cbc7d0b1491e740a8
d68a9110645bc80628a4ae2c420eadbc11ea6cff
c079a20472acae24f4a9cd75ec75be3320b339a3
43fcccf21dd779b73752111c1bba2c680b1b5929
d328104200a615c3fc1754bb72498ce635f3db75
```

I think the right thing to do is cherry-pick each one and fix any conflicts which emerge.

**Comment by thierrymarianne** [comment]
I've squashed most of suggested changes into https://github.com/cjdelisle/Matterfoss/pull/9/commits/61d9abd5778717d69c9f527dbaddfe89cc6657e4 (not all of them b/c there were related before to case, i don't think we ever claim to support ... e.g. cloud-related features or LDAP)

**Pull request closed without merging**
